In [1]:
import pandas as pd
import numpy as np
import matplotlib as plt

In [60]:
df = pd.read_excel("raw_data.xlsx",index_col = "Date")

In [61]:
df.head()

,ROST,AAPL,MA,ANSS,TSCO,NFLX,AMD,EZJ.L,SDR.L,GE,...,DPW.DE,BAS.DE,BA.L,RI.PA,BNP.PA,AI.PA,^GDAXI,^GSPC,^FCHI,^FTSE
Date,,,,,,,,,,,,,,,,,,,,,
2007-01-03,6.656907,10.391690,7.333238,22.094999,10.277849,3.801429,19.520000,533.848755,748.937744,23.043249,...,13.811960,20.548616,245.801102,63.071957,49.996510,34.699177,6691.319824,1416.599976,5610.919922,6319.000000
2007-01-04,6.814104,10.622340,7.693017,22.075001,10.376698,3.621428,19.790001,539.361328,737.518982,22.909737,...,13.865660,20.325109,242.962677,61.870964,49.879574,34.451363,6674.399902,1418.339966,5574.560059,6287.000000
2007-01-05,6.857771,10.546695,7.686932,22.000000,10.781073,3.544286,19.709999,552.930481,732.145264,22.794428,...,13.453985,20.184383,240.408249,61.252251,49.177856,33.917549,6593.089844,1409.709961,5517.350098,6220.100098
2007-01-08,6.897070,10.598778,7.688452,22.160000,10.484530,3.404286,19.469999,552.505920,733.824585,22.788364,...,13.585243,20.129198,238.279434,61.980171,49.177856,33.688751,6607.589844,1412.839966,5518.589844,6194.200195
2007-01-09,6.982220,11.479221,8.042907,21.764999,10.758605,3.427143,19.650000,549.962463,732.145264,22.788364,...,13.483815,20.258883,237.853714,61.325008,49.060909,33.898457,6614.370117,1412.109985,5533.029785,6196.100098

In [62]:
df.isna().sum()

ROST       0
AAPL       0
MA         0
ANSS       0
TSCO       0
NFLX       0
AMD        0
EZJ.L     69
SDR.L     70
GE         0
F          0
BATS.L    69
VOD.L     69
ADS.DE    59
DPW.DE    59
BAS.DE    59
BA.L      69
RI.PA     34
BNP.PA    34
AI.PA     34
^GDAXI    63
^GSPC      0
^FCHI     35
^FTSE      0
dtype: int64

In [63]:
df.interpolate(inplace=True)

In [65]:
df.isna().sum()

ROST      0
AAPL      0
MA        0
ANSS      0
TSCO      0
NFLX      0
AMD       0
EZJ.L     0
SDR.L     0
GE        0
F         0
BATS.L    0
VOD.L     0
ADS.DE    0
DPW.DE    0
BAS.DE    0
BA.L      0
RI.PA     0
BNP.PA    0
AI.PA     0
^GDAXI    0
^GSPC     0
^FCHI     0
^FTSE     0
dtype: int64

In [66]:
returns = pd.DataFrame()
columns = list(df.columns)
for name in columns:
    returns["srt_"+name] = df[name].pct_change()

In [67]:
returns.head()

,srt_ROST,srt_AAPL,srt_MA,srt_ANSS,srt_TSCO,srt_NFLX,srt_AMD,srt_EZJ.L,srt_SDR.L,srt_GE,...,srt_DPW.DE,srt_BAS.DE,srt_BA.L,srt_RI.PA,srt_BNP.PA,srt_AI.PA,srt_^GDAXI,srt_^GSPC,srt_^FCHI,srt_^FTSE
Date,,,,,,,,,,,,,,,,,,,,,
2007-01-03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2007-01-04,0.023614,0.022196,0.049061,-0.000905,0.009618,-0.047351,0.013832,0.010326,-0.015247,-0.005794,...,0.003888,-0.010877,-0.011548,-0.019042,-0.002339,-0.007142,-0.002529,0.001228,-0.006480,-0.005064
2007-01-05,0.006408,-0.007121,-0.000791,-0.003398,0.038969,-0.021302,-0.004043,0.025158,-0.007286,-0.005033,...,-0.029690,-0.006924,-0.010514,-0.010000,-0.014068,-0.015495,-0.012182,-0.006085,-0.010263,-0.010641
2007-01-08,0.005731,0.004938,0.000198,0.007273,-0.027506,-0.039500,-0.012177,-0.000768,0.002294,-0.000266,...,0.009756,-0.002734,-0.008855,0.011884,0.000000,-0.006746,0.002199,0.002220,0.000225,-0.004164
2007-01-09,0.012346,0.083070,0.046102,-0.017825,0.026141,0.006714,0.009245,-0.004603,-0.002288,0.000000,...,-0.007466,0.006443,-0.001787,-0.010571,-0.002378,0.006225,0.001026,-0.000517,0.002617,0.000307

In [68]:
returns.tail()

,srt_ROST,srt_AAPL,srt_MA,srt_ANSS,srt_TSCO,srt_NFLX,srt_AMD,srt_EZJ.L,srt_SDR.L,srt_GE,...,srt_DPW.DE,srt_BAS.DE,srt_BA.L,srt_RI.PA,srt_BNP.PA,srt_AI.PA,srt_^GDAXI,srt_^GSPC,srt_^FCHI,srt_^FTSE
Date,,,,,,,,,,,,,,,,,,,,,
2020-02-10,0.007068,0.004750,0.010031,0.005933,0.010150,0.011724,0.050875,-0.011586,0.010355,0.006235,...,-0.005047,0.004004,-0.009771,-0.003100,-0.003666,-0.001853,-0.001464,0.007326,-0.002335,-0.005077
2020-02-11,0.012177,-0.006033,0.001938,0.006178,0.000410,0.007061,0.029468,0.039518,0.008199,-0.004648,...,0.013528,0.007657,0.010792,-0.004975,0.021108,0.024137,0.009916,0.001688,0.006498,-0.002652
2020-02-12,0.003008,0.023748,0.009791,0.014465,0.009839,0.016912,0.001673,-0.015464,-0.009004,0.024124,...,0.008039,0.010923,0.000610,0.004062,0.016120,0.006527,0.008948,0.006463,0.008253,0.007050
2020-02-13,0.004498,-0.007121,0.005028,-0.002667,-0.002740,0.003658,0.011876,-0.014398,-0.012603,-0.016717,...,0.005718,-0.018478,0.008841,0.037971,-0.000187,0.008646,-0.000316,-0.001630,-0.001899,0.004667
2020-02-14,0.009784,0.000246,0.015216,0.001029,-0.000916,-0.002622,0.014304,-0.004980,0.003562,-0.008501,...,-0.004937,-0.002712,-0.028105,-0.004498,0.002053,-0.008571,-0.000089,0.001844,-0.003904,-0.010936

In [69]:
returns.isna().sum()

srt_ROST      1
srt_AAPL      1
srt_MA        1
srt_ANSS      1
srt_TSCO      1
srt_NFLX      1
srt_AMD       1
srt_EZJ.L     1
srt_SDR.L     1
srt_GE        1
srt_F         1
srt_BATS.L    1
srt_VOD.L     1
srt_ADS.DE    1
srt_DPW.DE    1
srt_BAS.DE    1
srt_BA.L      1
srt_RI.PA     1
srt_BNP.PA    1
srt_AI.PA     1
srt_^GDAXI    1
srt_^GSPC     1
srt_^FCHI     1
srt_^FTSE     1
dtype: int64

In [70]:
returns.dropna(inplace=True)

In [71]:
returns = returns.iloc[::-1]

In [72]:
cov_matrix = returns.cov()

In [73]:
corr_matrix = returns.corr()

In [74]:
us_stocks = ["ROST","AAPL","MA","ANSS","TSCO","NFLX","AMD","GE","F"]
uk_stocks = ["EZJ.L","SDR.L","BATS.L","VOD.L","BA.L"]
bundes_stocks = ["ADS.DE","DPW.DE","BAS.DE"]
fr_stocks = ["RI.PA","BNP.PA","AI.PA"]
us_index = "^GSPC"
uk_index = "^FTSE"
fr_index = "^FCHI"
bundes_index = "^GDAXI"

In [78]:
returns.columns

Index(['srt_ROST', 'srt_AAPL', 'srt_MA', 'srt_ANSS', 'srt_TSCO', 'srt_NFLX',
       'srt_AMD', 'srt_EZJ.L', 'srt_SDR.L', 'srt_GE', 'srt_F', 'srt_BATS.L',
       'srt_VOD.L', 'srt_ADS.DE', 'srt_DPW.DE', 'srt_BAS.DE', 'srt_BA.L',
       'srt_RI.PA', 'srt_BNP.PA', 'srt_AI.PA', 'srt_^GDAXI', 'srt_^GSPC',
       'srt_^FCHI', 'srt_^FTSE'],
      dtype='object')

In [84]:
returns_usd = returns[['srt_ROST', 'srt_AAPL', 'srt_MA', 'srt_ANSS', 'srt_TSCO', 'srt_NFLX','srt_AMD','srt_GE', 'srt_F','srt_^GSPC']]

In [85]:
returns_gbp = returns[['srt_EZJ.L', 'srt_SDR.L','srt_BATS.L','srt_VOD.L','srt_BA.L','srt_^FTSE']]

In [87]:
returns_eur = returns[['srt_ADS.DE', 'srt_DPW.DE', 'srt_BAS.DE','srt_RI.PA', 'srt_BNP.PA', 'srt_AI.PA','srt_^GDAXI','srt_^FCHI']]

In [124]:
betas_usd = pd.DataFrame(returns_usd.cov()["srt_^GSPC"]/returns_usd["srt_^GSPC"].var())

In [125]:
betas_usd.columns = ["Beta"]

In [126]:
betas_usd = betas_usd.T

In [127]:
betas_usd

,srt_ROST,srt_AAPL,srt_MA,srt_ANSS,srt_TSCO,srt_NFLX,srt_AMD,srt_GE,srt_F,srt_^GSPC
Beta,0.833583,1.002818,1.142105,1.041837,0.875036,0.991473,1.467142,1.125141,1.243178,1.0

In [116]:
betas_gbp = pd.DataFrame(returns_gbp.cov()["srt_^FTSE"]/returns_gbp["srt_^FTSE"].var())

In [117]:
betas_gbp.columns = ["Beta"]

In [200]:
beta_gbp = betas_gbp.T

In [201]:
beta_gbp

      srt_EZJ.L  srt_SDR.L  srt_BATS.L  srt_VOD.L  srt_BA.L  srt_^FTSE
Beta   0.202065    0.42157    0.204748   0.262302  0.235418        1.0

In [166]:
residuals_usd = pd.DataFrame()

for columns in returns_usd[returns_usd.columns[0:8]]:
    residuals_usd[columns] = returns_usd[columns] - returns_usd["srt_^GSPC"] * betas_usd[columns].values

In [204]:
residuals_gbp = pd.DataFrame()

for columns in returns_gbp.columns[0:5]:
    residuals_gbp[columns] = returns_gbp[columns] - returns_gbp["srt_^FTSE"] * beta_gbp[columns].values

In [205]:
residuals_gbp

            srt_EZJ.L  srt_SDR.L  srt_BATS.L  srt_VOD.L  srt_BA.L
Date
2020-02-14  -0.002770   0.008172   -0.007963  -0.008465 -0.025530
2020-02-13  -0.015341  -0.014570   -0.008149  -0.006989  0.007743
2020-02-12  -0.016888  -0.011976   -0.016766   0.013584 -0.001050
2020-02-11   0.040054   0.009317    0.003152   0.002829  0.011417
2020-02-10  -0.010560   0.012495    0.002782  -0.018532 -0.008576
2020-02-07  -0.016563  -0.001848   -0.011381   0.012594  0.002669
2020-02-06  -0.002136   0.003829    0.008541   0.025981  0.009175
2020-02-05   0.032596   0.008570   -0.002301  -0.032231 -0.007041
2020-02-04   0.024461   0.021478    0.014792   0.001334  0.008355
2020-02-03   0.041034   0.012018    0.012640   0.013592  0.019850
2020-01-31   0.006346  -0.002610    0.005168  -0.003753 -0.003099
2020-01-30  -0.015332   0.000145   -0.012463  -0.033645 -0.008209
2020-01-29  -0.002933  -0.001115    0.002994  -0.009066  0.006640
2020-01-28   0.005696   0.026667    0.008411   0.021308  0.005712
2020-01-27  -0.051349  -0.031655   -0.016787  -0.016793 -0.016435
2020-01-24   0.007480   0.018495    0.006891   0.017140  0.010139
2020-01-23  -0.033678  -0.010738    0.003110   0.011160 -0.000987
2020-01-22   0.007667   0.004395   -0.006236  -0.012807 -0.006500
2020-01-21   0.027345  -0.012374   -0.014814   0.004161  0.033373
2020-01-17  -0.005093   0.007140   -0.000733  -0.010584  0.012615
2020-01-16  -0.010465   0.005513   -0.011662  -0.013302  0.005258
2020-01-15  -0.006836  -0.008459    0.006343   0.008369  0.000677
2020-01-14   0.011267   0.004029   -0.003562   0.032284 -0.003080
2020-01-13  -0.005461  -0.004098    0.002932  -0.001159  0.034841
2020-01-10   0.042329  -0.003396    0.006924  -0.001754 -0.000021
2020-01-09   0.021406   0.008558   -0.003653   0.029434  0.000968
2020-01-08   0.027346  -0.005261    0.018617   0.005693  0.003019
2020-01-07   0.012602   0.002226    0.016754  -0.002807  0.002762
2020-01-06  -0.019735  -0.020769    0.000669  -0.004192  0.014884
2020-01-03  -0.034047  -0.016347    0.026159   0.000323  0.011286
...               ...        ...         ...        ...       ...
2007-02-15   0.001637  -0.007358   -0.006270  -0.006603  0.023956
2007-02-14   0.001267   0.015720    0.007290   0.002169  0.007494
2007-02-13   0.012623  -0.002881    0.000940  -0.007065  0.004509
2007-02-12  -0.001159  -0.016235   -0.002435   0.011901 -0.000206
2007-02-09   0.014818   0.018657    0.002005  -0.007359  0.015364
2007-02-08  -0.001480  -0.006349   -0.004520  -0.002613 -0.014034
2007-02-07  -0.022647  -0.001895    0.017646   0.010562 -0.007319
2007-02-06  -0.008846   0.008351    0.006216   0.001392  0.027224
2007-02-05   0.029425   0.000727   -0.002223   0.003870  0.005992
2007-02-02   0.020908   0.012626   -0.001967  -0.018321  0.002327
2007-02-01   0.011978   0.017239    0.007105   0.016838  0.012239
2007-01-31   0.006096   0.002605   -0.003940   0.006717 -0.011907
2007-01-30   0.018452  -0.008078   -0.006802  -0.013929  0.004901
2007-01-29   0.022165  -0.002648    0.029694   0.001728  0.002742
2007-01-26  -0.000144  -0.003252    0.013483  -0.004773 -0.014121
2007-01-25  -0.013906  -0.003200   -0.004199  -0.005339 -0.008541
2007-01-24  -0.007369   0.004811    0.000364   0.006315  0.016239
2007-01-23  -0.013333  -0.005477    0.000617   0.000791  0.003085
2007-01-22   0.007719   0.009088   -0.002883   0.005605 -0.020810
2007-01-19  -0.000189   0.001885   -0.016553   0.003144  0.002113
2007-01-18   0.008239   0.002586   -0.006133  -0.009578  0.001593
2007-01-17  -0.003160   0.000031    0.018758   0.007052 -0.002855
2007-01-16  -0.003919   0.016889   -0.004100  -0.006055  0.029633
2007-01-12  -0.011872  -0.003837    0.000367   0.001299 -0.009832
2007-01-11   0.003940   0.004109    0.014461   0.019347  0.017324
2007-01-10  -0.006556  -0.013646    0.023102  -0.023586 -0.012975
2007-01-09  -0.004665  -0.002418    0.017371   0.013477 -0.001859
2007-01-08   0.000074   0.004049   -0.003314   0.011366 -0.007875
2007-01-05   0.027308  -0.002800   -0.014215  -0.012386 -0.008009
2007-01-04   0.011349  -0.013112   -0.007093   0.021983 -0.010355

[3302 rows x 5 columns]